package gitx

import (
	"bufio"
	"os"
	"path"
	"path/filepath"
	"strings"
)

// Generated recognition. A review is about what somebody wrote, and a 4000-line
// lock file churn between two real changes is noise that hides them. dv still
// lists these files and still lets you open one, it just does not put the diff
// in front of you unasked.
//
// Three signals, cheapest first:
//
//   - the path, which covers lock files, vendored trees and the usual
//     protobuf/minified/snapshot naming;
//   - a "generated ... do not edit" banner near the top of the file, which is
//     the convention Go's stringer, mockgen, sqlc, protoc and many others
//     follow and the only way to catch a file named like handwritten code;
//   - .gitattributes marking it linguist-generated, which is how a repository
//     declares its own and therefore overrules the guesses above.

// generatedExts are suffixes that are generated wherever they appear.
var generatedExts = []string{
	".pb.go", ".pb.gw.go", "_pb2.py", "_pb2_grpc.py", ".pb.cc", ".pb.h", "_pb.js", "_pb.ts",
	".gen.go", ".generated.go", "_generated.go", "_string.go",
	".g.dart", ".freezed.dart", ".g.cs", ".designer.cs", ".g.kt",
	".min.js", ".min.css", ".min.mjs",
	".map", ".snap", ".pbxproj",
}

// generatedNames are whole file names that are always machine-written.
var generatedNames = map[string]bool{
	"package-lock.json": true, "yarn.lock": true, "pnpm-lock.yaml": true,
	"npm-shrinkwrap.json": true, "bun.lockb": true, "deno.lock": true,
	"cargo.lock": true, "poetry.lock": true, "pdm.lock": true, "uv.lock": true,
	"gemfile.lock": true, "composer.lock": true, "pipfile.lock": true,
	"gradle.lockfile": true, "packages.lock.json": true, "flake.lock": true,
	"go.sum": true, "mix.lock": true, "pubspec.lock": true, "podfile.lock": true,
}

// generatedDirs are path segments whose whole subtree is machine-written.
// Deliberately narrower than the indexer's skip list: "build" and "target" are
// real source directories in plenty of projects.
var generatedDirs = map[string]bool{
	"vendor": true, "node_modules": true, "__pycache__": true,
	"__snapshots__": true, "__generated__": true, ".yarn": true,
}

// generatedByPath reports whether a path alone is enough to call it generated.
func generatedByPath(p string) bool {
	lower := strings.ToLower(p)
	for _, seg := range strings.Split(lower, "/") {
		if generatedDirs[seg] {
			return true
		}
	}
	base := path.Base(lower)
	if generatedNames[base] {
		return true
	}
	for _, ext := range generatedExts {
		if strings.HasSuffix(base, ext) {
			return true
		}
	}
	// zz_generated.deepcopy.go and friends, the Kubernetes convention.
	return strings.HasPrefix(base, "zz_generated")
}

// bannerBytes is how much of a file's head is searched for a marker. Generators
// put it in the first line or two; anything further down is a file talking
// about generated code rather than being it.
const bannerBytes = 1024

// bannerLines bounds the search the same way for files with a long licence
// header above the marker.
const bannerLines = 20

var bannerMarkers = [][]string{
	{"code generated", "do not edit"},
	{"generated by", "do not edit"},
	{"@generated"},
	{"autogenerated", "do not edit"},
	{"automatically generated", "do not edit"},
	{"this file is generated"},
	{"do not edit this file"},
}

// hasGeneratedBanner looks for a generator's marker in the head of a file.
func hasGeneratedBanner(head []byte) bool {
	sc := bufio.NewScanner(strings.NewReader(string(head)))
	for n := 0; n < bannerLines && sc.Scan(); n++ {
		line := strings.ToLower(sc.Text())
		if len(line) > 300 {
			continue
		}
		for _, marker := range bannerMarkers {
			hit := true
			for _, part := range marker {
				if !strings.Contains(line, part) {
					hit = false
					break
				}
			}
			if hit {
				return true
			}
		}
	}
	return false
}

// headOfWorktreeFile reads the first bannerBytes of a path without pulling a
// whole lock file into memory just to look at its first line.
func (r *Repo) headOfWorktreeFile(p string) []byte {
	f, err := os.Open(filepath.Join(r.Root, p))
	if err != nil {
		return nil
	}
	defer f.Close()
	buf := make([]byte, bannerBytes)
	n, _ := f.Read(buf)
	return buf[:n]
}

// gitattributesGenerated asks git which of these paths the repository itself
// marks as generated. One batched call, and a failure just means no answer.
func (r *Repo) gitattributesGenerated(paths []string) map[string]bool {
	if len(paths) == 0 {
		return nil
	}
	out, err := r.runInput(strings.Join(paths, "\x00"),
		"check-attr", "--stdin", "-z", "linguist-generated")
	if err != nil {
		return nil
	}
	// -z output is a flat NUL-separated stream of path, attribute, value.
	fields := strings.Split(out, "\x00")
	marked := make(map[string]bool)
	for i := 0; i+2 < len(fields); i += 3 {
		if fields[i+1] == "linguist-generated" && (fields[i+2] == "set" || fields[i+2] == "true") {
			marked[fields[i]] = true
		}
	}
	return marked
}

// markGenerated fills in the Generated flag for a listed set of files.
func (r *Repo) markGenerated(entries []*FileEntry) {
	paths := make([]string, 0, len(entries))
	for _, e := range entries {
		paths = append(paths, e.Path)
	}
	declared := r.gitattributesGenerated(paths)

	for _, e := range entries {
		switch {
		case declared[e.Path]:
			e.Generated = true
		case generatedByPath(e.Path):
			e.Generated = true
		case e.Binary || e.Status == "D":
			// Nothing to read, and a deleted file's banner is not interesting.
		default:
			e.Generated = hasGeneratedBanner(r.headOfWorktreeFile(e.Path))
		}
	}
}
