package gitx

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

func TestGeneratedByPath(t *testing.T) {
	yes := []string{
		"api/service.pb.go", "api/service_grpc.pb.go", "proto/thing_pb2.py",
		"internal/kind_string.go", "zz_generated.deepcopy.go", "x/y.gen.go",
		"package-lock.json", "web/yarn.lock", "Cargo.lock", "go.sum",
		"vendor/github.com/x/y.go", "web/node_modules/react/index.js",
		"src/__snapshots__/App.test.js.snap", "static/app.min.js", "bundle.js.map",
		"lib/model.freezed.dart", "Forms/Main.Designer.cs",
	}
	for _, p := range yes {
		if !generatedByPath(p) {
			t.Errorf("%s: want generated", p)
		}
	}

	no := []string{
		"main.go", "internal/server/handlers.go", "src/App.jsx", "README.md",
		"go.mod", "package.json", "Makefile",
		// Near-misses that must stay visible.
		"build/config.go", "target/main.rs", "dist.go", "generator.go",
		"internal/codegen/codegen.go", "vendored_test.go", "mapper.go",
	}
	for _, p := range no {
		if generatedByPath(p) {
			t.Errorf("%s: want NOT generated", p)
		}
	}
}

func TestGeneratedBanner(t *testing.T) {
	yes := []string{
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage p\n",
		"// Code generated by \"stringer -type=Kind\"; DO NOT EDIT.\n",
		"/* Generated by webpack. Do not edit. */\n",
		"# @generated\nimport x\n",
		"<!-- This file is generated -->\n",
		"// Automatically generated, DO NOT EDIT\n",
		"/*\n * Copyright 2026 Someone\n * Licensed under Apache 2.0\n */\n\n// Code generated by mockgen. DO NOT EDIT.\n",
	}
	for _, src := range yes {
		if !hasGeneratedBanner([]byte(src)) {
			t.Errorf("want banner in %q", src)
		}
	}

	no := []string{
		"package main\n\nfunc main() {}\n",
		// Talking about generated code is not the same as being it.
		"// gen builds the generated files. Run it after changing the schema.\n",
		"// This parser was hand written for speed.\n",
		"",
		// Too far down to be a banner.
		"package p\n" + repeat("// filler\n", 40) + "// Code generated. DO NOT EDIT.\n",
	}
	for _, src := range no {
		if hasGeneratedBanner([]byte(src)) {
			t.Errorf("unexpected banner in %q", src)
		}
	}
}

func repeat(s string, n int) string {
	out := ""
	for i := 0; i < n; i++ {
		out += s
	}
	return out
}

// tempRepo builds a throwaway git repository with the given files committed.
func tempRepo(t *testing.T, files map[string]string) *Repo {
	t.Helper()
	root := t.TempDir()
	for _, args := range [][]string{
		{"init", "-q"}, {"config", "user.email", "t@dv"}, {"config", "user.name", "dv"},
	} {
		cmd := exec.Command("git", args...)
		cmd.Dir = root
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v: %s", args, err, out)
		}
	}
	for name, body := range files {
		p := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	repo, err := Open(root)
	if err != nil {
		t.Fatal(err)
	}
	return repo
}

func commitAll(t *testing.T, r *Repo, msg string) {
	t.Helper()
	for _, args := range [][]string{{"add", "-A"}, {"commit", "-q", "-m", msg}} {
		cmd := exec.Command("git", args...)
		cmd.Dir = r.Root
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v: %s", args, err, out)
		}
	}
}

func TestFilesMarksGenerated(t *testing.T) {
	repo := tempRepo(t, map[string]string{
		"main.go":           "package main\n\nfunc main() {}\n",
		"api/service.pb.go": "package api\n\nvar A = 1\n",
		"mock_store.go":     "// Code generated by mockgen. DO NOT EDIT.\n\npackage main\n",
		"package-lock.json": "{\"lockfileVersion\": 3}\n",
		"schema.sql":        "create table t (id int);\n",
		".gitattributes":    "schema.sql linguist-generated=true\n",
	})
	commitAll(t, repo, "base")

	// Touch every one of them so they all land in the working diff.
	for name := range map[string]bool{
		"main.go": true, "api/service.pb.go": true, "mock_store.go": true,
		"package-lock.json": true, "schema.sql": true,
	} {
		p := filepath.Join(repo.Root, name)
		b, err := os.ReadFile(p)
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, append(b, []byte("\n-- touched\n")...), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	scope, err := repo.ResolveScope("working", "")
	if err != nil {
		t.Fatal(err)
	}
	files, err := repo.Files(scope)
	if err != nil {
		t.Fatal(err)
	}

	got := map[string]bool{}
	for _, f := range files {
		got[f.Path] = f.Generated
	}
	want := map[string]bool{
		"main.go":           false, // handwritten
		"api/service.pb.go": true,  // by path
		"mock_store.go":     true,  // by banner, path says nothing
		"package-lock.json": true,  // by name
		"schema.sql":        true,  // declared in .gitattributes
	}
	for path, w := range want {
		if _, ok := got[path]; !ok {
			t.Errorf("%s missing from the file list", path)
			continue
		}
		if got[path] != w {
			t.Errorf("%s: Generated = %v, want %v", path, got[path], w)
		}
	}
}

func TestGeneratedFileStillDiffs(t *testing.T) {
	// Hiding the diff is the client's choice; the server must still serve it
	// when the reader asks to see it anyway.
	repo := tempRepo(t, map[string]string{"go.sum": "a v1.0.0 h1:xxx\n"})
	commitAll(t, repo, "base")
	if err := os.WriteFile(filepath.Join(repo.Root, "go.sum"), []byte("a v1.0.0 h1:yyy\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	scope, err := repo.ResolveScope("working", "")
	if err != nil {
		t.Fatal(err)
	}
	files, err := repo.Files(scope)
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 || !files[0].Generated {
		t.Fatalf("want one generated file, got %+v", files)
	}
	fd, err := repo.Diff(scope, files[0])
	if err != nil {
		t.Fatal(err)
	}
	if len(fd.NewLines) == 0 || !fd.Generated {
		t.Fatalf("diff should still be produced and stay flagged: %+v", fd.FileEntry)
	}
}
